<div class="p-a-1">
<h1>URL cho Service</h1>
<form method="post">
    <div class="form-group">
        <label>Nội dung config url cho mục dịch vụ, chý ý thêm vào application.config.php</label>
        <pre style="background: silver;">        
            'config/autoload/{,*.}{global,local,<label>service</label>}.php' 
        </pre>
        <textarea class="form-control" name="content" style="height: 500px;"><?=$this->content?></textarea>
    </div>
    <div class="form-group">
        <button class="btn btn-danger">Save</button>
    </div>
</form>
</div>